### ISSUE TITLE
Broken on tModLoader version 2024.3.3.0?

### ISSUE THREAD

**Issue by craftytim** [DominicKarma/WrathOfTheGodsPublic#33]
tModLoader says an error occurred during loading, and the issue goes away when I disable WoTG. 
It reports that the `'ShakeInfo` method was not found in Luminance - possible typo?

Relevant error log: 

[21:33:06.503] [.NET TP Worker/ERROR] [tML]: An error occurred while loading 
The mod responsible is unknown and tModLoader must be restarted.
Terraria.ModLoader.Exceptions.JITException: 
In NoxusBoss.Content.Projectiles.TerminusProj.AI, Method not found: 'ShakeInfo Luminance.Core.Graphics.ScreenShakeSystem.SetUniversalRumble(Single, Single, System.Nullable`1<Microsoft.Xna.Framework.Vector2>, Single)'.
In NoxusBoss.Content.Projectiles.TerminusProj.DoBehavior_ChargeEnergy, Method not found: 'ShakeInfo Luminance.Core.Graphics.ScreenShakeSystem.SetUniversalRumble(Single, Single, System.Nullable`1<Microsoft.Xna.Framework.Vector2>, Single)'.
In NoxusBoss.Content.Projectiles.TerminusProj.DoBehavior_OpenEye, Method not found: 'ShakeInfo Luminance.Core.Graphics.ScreenShakeSystem.SetUniversalRumble(Single, Single, System.Nullable`1<Microsoft.Xna.Framework.Vector2>, Single)'.
In NoxusBoss.Content.Projectiles.Typeless.ThePurifierProj.AI, Method not found: 'ShakeInfo Luminance.Core.Graphics.ScreenShakeSystem.SetUniversalRumble(Single, Single, System.Nullable`1<Microsoft.Xna.Framework.Vector2>, Single)'.
In NoxusBoss.Content.NPCs.Bosses.NamelessDeity.NamelessDeityBoss.DoBehavior_Awaken, Method not found: 'ShakeInfo Luminance.Core.Graphics.ScreenShakeSystem.SetUniversalRumble(Single, Single, System.Nullable`1<Microsoft.Xna.Framework.Vector2>, Single)'.

   at Terraria.ModLoader.Core.AssemblyManager.JITAssembliesAsync(IEnumerable`1 assemblies, PreJITFilter filter, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 419
   at Terraria.ModLoader.ModContent.JITModsAsync(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 384
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 311
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 132
[21:36:28.733] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs"

**Comment by DominicKarma** [comment]
Just to be clear, is your Luminance version at 1.0.3? I've heard a litany of cases where people have oddities regarding automatic downloading of the library. It would not surprise me if the version is actually outdated and the reason the method throw this exception is because it doesn't exist.

**Comment by craftytim** [comment]
I will go check. Thank you for the fast reply =D

**Comment by craftytim** [comment]
Yes, this solved the problem! :D
